---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: resources/content/posts
  label: Posts
  create: documents
  match: "*.md"
  new_doc_ext: md
  templates:
  - blog-post
- type: heading
  label: Static
- type: document
  path: resources/content/static/me.md
  label: Me
- type: document
  path: resources/content/static/uses.md
  label: Uses
- type: document
  path: resources/content/static/resume.md
  label: Resume
- type: document
  path: resources/content/static/portfolio.md
  label: Portfolio
  match: "**/*"
- type: document
  path: resources/content/static/charity.md
  label: Charity
- type: heading
  label: Legal
- type: document
  path: resources/content/static/privacy.md
  label: Privacy
- type: document
  path: resources/content/static/imprint.md
  label: Imprint
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
